[package]
name = "graph_querying"
version = "0.1.0"
edition = "2021"


[dependencies]
chrono = "0.4"
csv = "1.3.0"
env_logger = "0.10"
log = "0.4.22"
reqwest = "0.11"
serde = "1.0.204"
serde_json = "1.0.120"
serde_derive = "1.0.204"
tokio = { version = "1", features = ["full"] }
